/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 1280
      height: 720
      scale: 0.5
      fx: 906.496337890625
      fy: 906.1392822265625
      cx: 640.511962890625
      cy: 372.7534484863281
      d0: 0.0
      d1: 0.0
      d2: 0.0
      d3: 0.0
